### ISSUE TITLE
Add default classification if unknown honeypot peerType in put-service/worker.py

### ISSUE THREAD

**Issue by vorband** [schmalle/put-service#4]
To avoid api responses like the following, a default peerType should be set to "Unclassified" or something similar in https://github.com/schmalle/put-service/blob/2acbc188d94f3a233dca94e547ff57386469e542/worker.py#L15

{
 "AlertCountPerType": {
   **"": 1,**
   "Network(honeytrap)": 15,
   "Webpage": 2
 },
 "AlertCountTotal": 18
}

**Comment by schmalle** [comment]
fixed, please test

**Comment by vorband** [comment]
still giving me empty responses for /alert/retrieveAlertsCountWithType?time=3 (<- last 3 mins)
{
  "AlertCountPerType": {
    **"": 3,** 
    "Network(honeytrap)": 265, 
    "SSH/console(cowrie)": 17, 
    "Webpage": 81
  }, 
  "AlertCountTotal": 366
}
